import * as fs from 'fs';
import { FileAnalysis, IssueCategory } from '../types';

/**
 * HTML Reporter - generates interactive HTML reports
 */
export class HTMLReporter {
  generateReport(analyses: FileAnalysis[], outputPath: string): void {
    const html = this.buildHTML(analyses);
    fs.writeFileSync(outputPath, html, 'utf-8');
    console.log(`HTML report generated: ${outputPath}`);
  }

  private buildHTML(analyses: FileAnalysis[]): string {
    const totalIssues = analyses.reduce((sum, a) => sum + a.totalIssues, 0);
    const totalFunctions = analyses.reduce((sum, a) => sum + a.functions.length, 0);
    const totalClasses = analyses.reduce((sum, a) => sum + a.classes.length, 0);

    const issuesByCategory = this.groupIssuesByCategory(analyses);
    const issuesBySeverity = this.groupIssuesBySeverity(analyses);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Code Complexity Analysis Report</title>
  <style>
    ${this.getCSS()}
  </style>
</head>
<body>
  <header>
    <h1>📊 Code Complexity Analysis Report</h1>
    <p class="subtitle">Generated ${new Date().toLocaleString()}</p>
  </header>

  <div class="container">
    <!-- Summary Section -->
    <section class="summary">
      <h2>Summary</h2>
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-value">${analyses.length}</div>
          <div class="stat-label">Files Analyzed</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">${totalFunctions}</div>
          <div class="stat-label">Functions</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">${totalClasses}</div>
          <div class="stat-label">Classes</div>
        </div>
        <div class="stat-card ${totalIssues > 0 ? 'warning' : ''}">
          <div class="stat-value">${totalIssues}</div>
          <div class="stat-label">Total Issues</div>
        </div>
      </div>
    </section>

    <!-- Issues by Category -->
    <section class="chart-section">
      <h2>Issues by Category</h2>
      <div class="chart-container">
        ${this.buildBarChart(issuesByCategory, 'category')}
      </div>
    </section>

    <!-- Issues by Severity -->
    <section class="chart-section">
      <h2>Issues by Severity</h2>
      <div class="chart-container">
        ${this.buildBarChart(issuesBySeverity, 'severity')}
      </div>
    </section>

    <!-- File Details -->
    <section class="file-details">
      <h2>File Analysis Details</h2>
      ${analyses.map(a => this.buildFileCard(a)).join('')}
    </section>
  </div>

  <footer>
    <p>Generated by Code Complexity Analyzer</p>
  </footer>

  <script>
    ${this.getJavaScript()}
  </script>
</body>
</html>`;
  }

  private buildFileCard(analysis: FileAnalysis): string {
    const metrics = analysis.overallMetrics;
    const complexityLevel = this.getComplexityLevel(metrics.cyclomaticComplexity);

    return `
    <div class="file-card">
      <div class="file-header">
        <h3>${analysis.filePath}</h3>
        <span class="badge ${analysis.language.toLowerCase()}">${analysis.language}</span>
      </div>

      <div class="metrics-grid">
        <div class="metric">
          <span class="metric-label">Cyclomatic Complexity</span>
          <span class="metric-value ${complexityLevel}">${metrics.cyclomaticComplexity}</span>
        </div>
        <div class="metric">
          <span class="metric-label">Cognitive Complexity</span>
          <span class="metric-value">${metrics.cognitiveComplexity}</span>
        </div>
        <div class="metric">
          <span class="metric-label">Lines of Code</span>
          <span class="metric-value">${metrics.linesOfCode}</span>
        </div>
        <div class="metric">
          <span class="metric-label">Functions</span>
          <span class="metric-value">${analysis.functions.length}</span>
        </div>
        <div class="metric">
          <span class="metric-label">Issues</span>
          <span class="metric-value ${analysis.totalIssues > 0 ? 'warning' : ''}">${analysis.totalIssues}</span>
        </div>
      </div>

      ${analysis.totalIssues > 0 ? this.buildIssuesList(analysis) : ''}
      ${analysis.functions.length > 0 ? this.buildFunctionsList(analysis) : ''}
    </div>`;
  }

  private buildIssuesList(analysis: FileAnalysis): string {
    const allIssues: Array<{issue: any, source: string}> = [];

    analysis.functions.forEach(fn => {
      fn.issues.forEach(issue => {
        allIssues.push({ issue, source: `Function: ${fn.name}` });
      });
    });

    analysis.classes.forEach(cls => {
      cls.methods.forEach(method => {
        method.issues.forEach(issue => {
          allIssues.push({ issue, source: `Class: ${cls.name}.${method.name}` });
        });
      });
    });

    if (allIssues.length === 0) return '';

    return `
    <details class="issues-details">
      <summary>Issues (${allIssues.length})</summary>
      <div class="issues-list">
        ${allIssues.map(({issue, source}) => `
          <div class="issue-item severity-${issue.severity}">
            <div class="issue-header">
              <span class="issue-badge ${issue.category.toLowerCase()}">${issue.category}</span>
              <span class="severity-badge ${issue.severity}">${issue.severity}</span>
            </div>
            <div class="issue-message">${issue.message}</div>
            <div class="issue-source">Line ${issue.line} in ${source}</div>
            ${issue.suggestion ? `<div class="issue-suggestion">💡 ${issue.suggestion}</div>` : ''}
            ${issue.fix ? `
              <details class="fix-details">
                <summary>Suggested Fix</summary>
                <div class="fix-content">
                  <div class="fix-description">${issue.fix.description}</div>
                  ${issue.fix.automated ? '<span class="badge automated">Auto-fixable</span>' : ''}
                </div>
              </details>
            ` : ''}
          </div>
        `).join('')}
      </div>
    </details>`;
  }

  private buildFunctionsList(analysis: FileAnalysis): string {
    const topComplexFunctions = analysis.functions
      .sort((a, b) => b.metrics.cyclomaticComplexity - a.metrics.cyclomaticComplexity)
      .slice(0, 5);

    if (topComplexFunctions.length === 0) return '';

    return `
    <details class="functions-details">
      <summary>Top Complex Functions</summary>
      <table class="functions-table">
        <thead>
          <tr>
            <th>Function</th>
            <th>Cyclomatic</th>
            <th>Cognitive</th>
            <th>Lines</th>
            <th>Issues</th>
          </tr>
        </thead>
        <tbody>
          ${topComplexFunctions.map(fn => `
            <tr>
              <td><code>${fn.name}</code></td>
              <td class="${this.getComplexityLevel(fn.metrics.cyclomaticComplexity)}">${fn.metrics.cyclomaticComplexity}</td>
              <td>${fn.metrics.cognitiveComplexity}</td>
              <td>${fn.metrics.linesOfCode}</td>
              <td>${fn.issues.length}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </details>`;
  }

  private buildBarChart(data: Map<string, number>, type: string): string {
    const entries = Array.from(data.entries());
    const max = Math.max(...entries.map(([, count]) => count));

    return `
    <div class="bar-chart">
      ${entries.map(([label, count]) => {
        const percentage = max > 0 ? (count / max) * 100 : 0;
        return `
          <div class="bar-row">
            <div class="bar-label">${label}</div>
            <div class="bar-container">
              <div class="bar ${type === 'severity' ? label.toLowerCase() : ''}" style="width: ${percentage}%"></div>
              <span class="bar-value">${count}</span>
            </div>
          </div>
        `;
      }).join('')}
    </div>`;
  }

  private groupIssuesByCategory(analyses: FileAnalysis[]): Map<string, number> {
    const counts = new Map<string, number>();

    analyses.forEach(analysis => {
      analysis.functions.forEach(fn => {
        fn.issues.forEach(issue => {
          counts.set(issue.category, (counts.get(issue.category) || 0) + 1);
        });
      });

      analysis.classes.forEach(cls => {
        cls.methods.forEach(method => {
          method.issues.forEach(issue => {
            counts.set(issue.category, (counts.get(issue.category) || 0) + 1);
          });
        });
      });
    });

    return counts;
  }

  private groupIssuesBySeverity(analyses: FileAnalysis[]): Map<string, number> {
    const counts = new Map<string, number>();

    analyses.forEach(analysis => {
      analysis.functions.forEach(fn => {
        fn.issues.forEach(issue => {
          counts.set(issue.severity, (counts.get(issue.severity) || 0) + 1);
        });
      });

      analysis.classes.forEach(cls => {
        cls.methods.forEach(method => {
          method.issues.forEach(issue => {
            counts.set(issue.severity, (counts.get(issue.severity) || 0) + 1);
          });
        });
      });
    });

    return counts;
  }

  private getComplexityLevel(complexity: number): string {
    if (complexity <= 5) return 'low';
    if (complexity <= 10) return 'medium';
    if (complexity <= 20) return 'high';
    return 'critical';
  }

  private getCSS(): string {
    return `
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        background: #f5f7fa;
        color: #2c3e50;
        line-height: 1.6;
      }
      header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 2rem;
        text-align: center;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
      }
      h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
      .subtitle { opacity: 0.9; }
      .container { max-width: 1200px; margin: 2rem auto; padding: 0 1rem; }
      section { background: white; border-radius: 8px; padding: 2rem; margin-bottom: 2rem; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
      h2 { color: #667eea; margin-bottom: 1.5rem; font-size: 1.5rem; }
      .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.5rem; }
      .stat-card {
        text-align: center;
        padding: 1.5rem;
        background: #f8f9fa;
        border-radius: 8px;
        border: 2px solid #e9ecef;
      }
      .stat-card.warning { background: #fff3cd; border-color: #ffc107; }
      .stat-value { font-size: 2.5rem; font-weight: bold; color: #667eea; }
      .stat-card.warning .stat-value { color: #ff6b6b; }
      .stat-label { color: #6c757d; margin-top: 0.5rem; }
      .file-card { background: #f8f9fa; padding: 1.5rem; border-radius: 8px; margin-bottom: 1.5rem; border-left: 4px solid #667eea; }
      .file-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem; }
      .file-header h3 { color: #2c3e50; font-size: 1.2rem; }
      .badge {
        padding: 0.25rem 0.75rem;
        border-radius: 12px;
        font-size: 0.875rem;
        font-weight: 600;
        text-transform: uppercase;
      }
      .badge.javascript { background: #f7df1e; color: #000; }
      .badge.typescript { background: #3178c6; color: #fff; }
      .badge.python { background: #3776ab; color: #fff; }
      .badge.automated { background: #28a745; color: #fff; }
      .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 1rem; }
      .metric { display: flex; justify-content: space-between; padding: 0.5rem; background: white; border-radius: 4px; }
      .metric-label { color: #6c757d; font-size: 0.875rem; }
      .metric-value { font-weight: 600; }
      .metric-value.low { color: #28a745; }
      .metric-value.medium { color: #ffc107; }
      .metric-value.high { color: #fd7e14; }
      .metric-value.critical { color: #dc3545; }
      .metric-value.warning { color: #ff6b6b; }
      details { margin-top: 1rem; }
      summary {
        cursor: pointer;
        padding: 0.75rem;
        background: white;
        border-radius: 4px;
        font-weight: 600;
        color: #667eea;
        user-select: none;
      }
      summary:hover { background: #f0f0f0; }
      .issues-list, .functions-table { margin-top: 1rem; }
      .issue-item {
        padding: 1rem;
        margin-bottom: 0.75rem;
        background: white;
        border-left: 4px solid #6c757d;
        border-radius: 4px;
      }
      .issue-item.severity-low { border-left-color: #28a745; }
      .issue-item.severity-medium { border-left-color: #ffc107; }
      .issue-item.severity-high { border-left-color: #fd7e14; }
      .issue-item.severity-critical { border-left-color: #dc3545; }
      .issue-header { display: flex; gap: 0.5rem; margin-bottom: 0.5rem; }
      .issue-badge { padding: 0.2rem 0.6rem; background: #667eea; color: white; border-radius: 4px; font-size: 0.75rem; }
      .severity-badge {
        padding: 0.2rem 0.6rem;
        border-radius: 4px;
        font-size: 0.75rem;
        text-transform: uppercase;
        font-weight: 600;
      }
      .severity-badge.low { background: #28a745; color: white; }
      .severity-badge.medium { background: #ffc107; color: #000; }
      .severity-badge.high { background: #fd7e14; color: white; }
      .severity-badge.critical { background: #dc3545; color: white; }
      .issue-message { font-weight: 500; margin-bottom: 0.5rem; }
      .issue-source { color: #6c757d; font-size: 0.875rem; }
      .issue-suggestion { margin-top: 0.5rem; padding: 0.5rem; background: #e7f3ff; border-radius: 4px; font-size: 0.875rem; }
      .fix-details { margin-top: 0.5rem; }
      .fix-content { padding: 0.75rem; background: #f1f3f5; border-radius: 4px; margin-top: 0.5rem; }
      .fix-description { margin-bottom: 0.5rem; }
      .functions-table { width: 100%; border-collapse: collapse; }
      .functions-table th { background: #f8f9fa; padding: 0.75rem; text-align: left; }
      .functions-table td { padding: 0.75rem; border-top: 1px solid #dee2e6; }
      .functions-table code { background: #f1f3f5; padding: 0.2rem 0.4rem; border-radius: 3px; }
      .bar-chart { margin-top: 1rem; }
      .bar-row { margin-bottom: 1rem; }
      .bar-label { font-weight: 600; margin-bottom: 0.25rem; }
      .bar-container {
        display: flex;
        align-items: center;
        background: #f1f3f5;
        border-radius: 4px;
        overflow: hidden;
        height: 32px;
      }
      .bar {
        height: 100%;
        background: #667eea;
        transition: width 0.3s;
        min-width: 2px;
      }
      .bar.critical { background: #dc3545; }
      .bar.high { background: #fd7e14; }
      .bar.medium { background: #ffc107; }
      .bar.low { background: #28a745; }
      .bar-value {
        padding: 0 0.75rem;
        font-weight: 600;
        font-size: 0.875rem;
      }
      footer {
        text-align: center;
        padding: 2rem;
        color: #6c757d;
      }
    `;
  }

  private getJavaScript(): string {
    return `
      // Toggle details on click
      document.querySelectorAll('summary').forEach(summary => {
        summary.addEventListener('click', (e) => {
          const details = e.target.closest('details');
          if (details) {
            details.open = !details.open;
          }
        });
      });

      // Animate bars on load
      window.addEventListener('load', () => {
        document.querySelectorAll('.bar').forEach(bar => {
          const width = bar.style.width;
          bar.style.width = '0%';
          setTimeout(() => {
            bar.style.width = width;
          }, 100);
        });
      });
    `;
  }
}
